name: publish
on:
  push:
    tags:
      - 'v*'
jobs:
  build-webui:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build

      - name: publish
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{secrets.FTP_HOST}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: ./dist/webui/browser/
          port: 21
          protocol: ftps
